<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_Profile</name>
   <tag></tag>
   <elementGuidId>f8a9b0c1-1111-2222-3333-444455556666</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[href='profile.php#profile']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Profile')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Profile</value>
      <webElementGuid>f8a9b0c1-1111-2222-3333-444455556661</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Profile')]</value>
      <webElementGuid>f8a9b0c1-1111-2222-3333-444455556662</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
